name: Latest note post workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-note:
    name: Update this repo's README with latest note posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "NOTE"
          feed_list: "https://note.com/digiangler777/rss"
