name: Latest Qiita post workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"

jobs:
  update-readme-with-Qiita:
    name: Update this repo's README with latest Qiita posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://qiita.com/digiangler/feed.atom"
